"""added new field to transaction

Revision ID: 114e6b9ab465
Revises: 3ef674cd664e
Create Date: 2020-02-11 16:37:41.819051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114e6b9ab465'
down_revision = '3ef674cd664e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_enddate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('recurring_enddate')

    # ### end Alembic commands ###
