"""removed second account from transaction

Revision ID: 3ef674cd664e
Revises: 9b5393afda96
Create Date: 2020-02-11 11:53:42.468902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef674cd664e'
down_revision = '9b5393afda96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_transaction_account_to_id_account', type_='foreignkey')
        batch_op.drop_constraint('fk_transaction_account_from_id_account', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transaction_account_id_account'), 'account', ['account_id'], ['account_id'])
        batch_op.drop_column('account_from_id')
        batch_op.drop_column('account_to_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_to_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('account_from_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_transaction_account_id_account'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transaction_account_from_id_account', 'account', ['account_from_id'], ['account_id'])
        batch_op.create_foreign_key('fk_transaction_account_to_id_account', 'account', ['account_to_id'], ['account_id'])
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
