"""added transaction table

Revision ID: 9b5393afda96
Revises: c503bcb3014e
Create Date: 2020-02-11 01:54:34.405112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5393afda96'
down_revision = 'c503bcb3014e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_from_id', sa.Integer(), nullable=True),
    sa.Column('account_to_id', sa.Integer(), nullable=True),
    sa.Column('transaction_name', sa.String(length=40)),
    sa.Column('amount', sa.Numeric(scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_delay', sa.Interval(), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('delete_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_from_id'], ['account.account_id'], name=op.f('fk_transaction_account_from_id_account')),
    sa.ForeignKeyConstraint(['account_to_id'], ['account.account_id'], name=op.f('fk_transaction_account_to_id_account')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_transaction_user_id_user')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transaction'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
