"""changed networth precision

Revision ID: c503bcb3014e
Revises: fb6643960b15
Create Date: 2020-02-11 00:38:52.039237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c503bcb3014e'
down_revision = 'fb6643960b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account_networth',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(scale=2),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('networth',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('networth',
               existing_type=sa.Numeric(scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account_networth',
               existing_type=sa.Numeric(scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
