"""account_name not unique

Revision ID: fb6643960b15
Revises: 00c6c3d702aa
Create Date: 2020-02-10 15:08:34.982878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6643960b15'
down_revision = '00c6c3d702aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('uq_account_account_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_account_account_name', ['account_name'])

    # ### end Alembic commands ###
